### ISSUE TITLE
About Parameters to optimized

### ISSUE THREAD

**Issue by wkMvg** [Linusnie/robust-triangulation-relaxations#2]
Firstly, what a amazing job you done.
Secondly, I wonder if poses as a optimized parameter in your minimize triangulation? thx for your reply

**Comment by wkMvg** [comment]
<img width="637" alt="微信图片_20230421192415" src="https://user-images.githubusercontent.com/48551366/233624433-eafa3a09-09a0-498a-82a9-1c65f74f1484.png">

I see...... thank you

**Comment by Linusnie** [comment]
hi, thanks for the interest! Since this work is about triangulation the poses are always fixed parameters, though it's possible to do the same for fixed points and unknown poses (eg see this paper example 5 https://arxiv.org/pdf/2109.03349.pdf for point-to-line distance residuals)

**Comment by wkMvg** [comment]
> 

thanks for your reply.
