### ISSUE TITLE
Increase the scale of triangulation problem

### ISSUE THREAD

**Issue by ericzzj1989** [Linusnie/robust-triangulation-relaxations#4]
Hi,

Thanks for your amazing work!

Currently, the code appears to support a maximum of 30 poses. I attempted to increase this limit to 150, but encountered an issue where the program failed to run. I was wondering if it's possible to scale up the triangulation to handle more poses? Could you clarify the current limitations?

Thanks for your time!

**Comment by Linusnie** [comment]
hi, unfortunately, the size of the SDP grows rather rapidly with the number of poses (see Table 1 in the paper), meaning that you eventually run into memory issues. 

However, the constraints are very sparse. So switching to a solver that makes better use of sparsity (such as https://github.com/rangell/usbs) might increase the limit, but I have not tried that myself

**Comment by ericzzj1989** [comment]
Hi @Linusnie,

Thank you for your detailed explanation! I will try USBS and see how it handles the increased number of poses.

I am currently working on scaling the problem to handle a larger scale, and I am also wondering how to address robustness as the problem grows in size. Do you have any thoughts or recommendations on improving robustness in such large-scale scenarios?

If this is a topic that interests you, I would like to explore the possibility of collaborating on this.

**Comment by Linusnie** [comment]
I'd be very interested to collaborate in this direction! I'll shoot you an email

As far as robustness goes, there are essentially two limiting factors: 1) the loss function itself (in this case TLS - but other variants are also possible https://arxiv.org/pdf/2109.03349). and 2) the tightness of the relaxation, which degrades with the amount of noise and outliers (Fig. 3). In my experience, the fractional relaxation is pretty much always tight except for extreme cases, but it also has many more constraints/variables

**Comment by ericzzj1989** [comment]
Hi @Linusnie，

Thank you for your insights and valuable explanation!

I'm very glad you're interested! I received your email, and I look forward to discussing further! 😉
